// <auto-generated />
namespace QLDiemHocSinh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnhGV_giaovien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnhGV_giaovien));
        
        string IMigrationMetadata.Id
        {
            get { return "202110160818291_AnhGV_giaovien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
